/**
 * Document Generator
 * Generates markdown documentation from repo_facts.json
 */

import type { RepoFacts, BootcampOptions } from "./types.js";

/**
 * Format confidence as a badge
 */
function confidenceBadge(confidence?: "high" | "medium" | "low"): string {
  if (!confidence) return "";
  const badges: Record<string, string> = {
    high: "![Confidence: High](https://img.shields.io/badge/confidence-high-brightgreen)",
    medium: "![Confidence: Medium](https://img.shields.io/badge/confidence-medium-yellow)",
    low: "![Confidence: Low](https://img.shields.io/badge/confidence-low-red)",
  };
  return badges[confidence] || "";
}

/**
 * Format sources as a collapsible section
 */
function sourcesSection(sources?: string[], label = "Sources"): string {
  if (!sources || sources.length === 0) return "";
  return `
<details>
<summary>${label}</summary>

${sources.map(s => `- \`${s}\``).join("\n")}

</details>
`;
}

/**
 * Generate BOOTCAMP.md - the main 1-page overview
 */
export function generateBootcamp(facts: RepoFacts, _options: BootcampOptions): string {
  void _options;
  const prereqs = facts.quickstart.prerequisites.map((p) => `- ${p}`).join("\n");
  const steps = facts.quickstart.steps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  const commands = facts.quickstart.commands
    .slice(0, 5)
    .map((c) => `\`${c.command}\``)
    .join(", ");

  const keyDirs = facts.structure.keyDirs
    .slice(0, 5)
    .map((d) => `- \`${d.path}\` - ${d.purpose}`)
    .join("\n");

  const quickTasks = facts.firstTasks
    .filter((t) => t.difficulty === "beginner")
    .slice(0, 3)
    .map((t) => `- **${t.title}**: ${t.description}`)
    .join("\n");

  return `# ${facts.repoName} Bootcamp

${confidenceBadge(facts.confidence)}

> ${facts.purpose}

${facts.description}
${sourcesSection(facts.sources, "Based on")}

## Quick Facts

| | |
|---|---|
| **Languages** | ${facts.stack.languages.join(", ")} |
| **Frameworks** | ${facts.stack.frameworks.join(", ") || "None"} |
| **Build System** | ${facts.stack.buildSystem} |
| **Package Manager** | ${facts.stack.packageManager || "N/A"} |

## Prerequisites

${prereqs}

## Quick Start

${steps}

**Key commands:** ${commands}

## Project Structure

${keyDirs}

## If You Only Have 30 Minutes

1. Read this document
2. Run the dev server: \`${facts.quickstart.commands.find((c) => c.name.includes("dev"))?.command || facts.quickstart.commands[0]?.command || "npm run dev"}\`
3. Pick one of these starter tasks:

${quickTasks}

## Next Steps

- 📖 [ONBOARDING.md](./ONBOARDING.md) - Full setup guide
- 🏗️ [ARCHITECTURE.md](./ARCHITECTURE.md) - System design
- 🗺️ [CODEMAP.md](./CODEMAP.md) - Directory tour
- ✅ [FIRST_TASKS.md](./FIRST_TASKS.md) - Starter issues

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
}

/**
 * Generate ONBOARDING.md - detailed setup guide
 */
export function generateOnboarding(facts: RepoFacts): string {
  const prereqs = facts.quickstart.prerequisites.map((p) => `- [ ] ${p}`).join("\n");
  const commands = facts.quickstart.commands
    .map((c) => `### ${c.name}\n\`\`\`bash\n${c.command}\n\`\`\`\n${c.description ? `> ${c.description}` : ""}`)
    .join("\n\n");

  const errors = facts.quickstart.commonErrors
    ?.map((e) => `### ${e.error}\n**Fix:** ${e.fix}`)
    .join("\n\n") || "_No common errors documented_";

  const testDirs = facts.structure.testDirs.map((d) => `- \`${d}\``).join("\n");
  const testCmd = facts.quickstart.commands.find(
    (c) => c.name.includes("test") || c.command.includes("test")
  );

  return `# Onboarding Guide: ${facts.repoName}

## Prerequisites Checklist

${prereqs}

## Clone & Install

\`\`\`bash
# Clone the repository
git clone https://github.com/${facts.repoName}.git
cd ${facts.repoName.split("/")[1]}

# Install dependencies
${facts.quickstart.commands.find((c) => c.name === "install")?.command || `${facts.stack.packageManager || "npm"} install`}
\`\`\`

## Available Commands

${commands}

## Development Loop

1. Start the dev server/watch mode
2. Make changes to files in \`${facts.structure.keyDirs[0]?.path || "src/"}\`
3. Changes should hot-reload (if applicable)
4. Run tests before committing

## Running Tests

${testCmd ? `\`\`\`bash\n${testCmd.command}\n\`\`\`` : "_No test command detected_"}

Test directories:
${testDirs || "_No test directories detected_"}

## Common Errors & Fixes

${errors}

## Editor Setup

${facts.contrib.codeStyle ? `This project uses: **${facts.contrib.codeStyle}**` : "Check for .editorconfig, .prettierrc, or eslint config files."}

Recommended extensions:
- ESLint / Prettier (if applicable)
- Language-specific extensions for ${facts.stack.languages.join(", ")}

## Getting Help

- Check existing issues on GitHub
- Read through the docs in \`${facts.structure.docsDirs[0] || "docs/"}\`
- Look at existing code for patterns

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
}

/**
 * Generate ARCHITECTURE.md
 */
export function generateArchitecture(facts: RepoFacts): string {
  const components = facts.architecture.components
    .map((c) => `### ${c.name}\n\n**Directory:** \`${c.directory}\`\n\n${c.description}`)
    .join("\n\n");

  const abstractions = facts.architecture.keyAbstractions
    ?.map((a) => `- **${a.name}**: ${a.description}`)
    .join("\n") || "_None documented_";

  // Generate code examples section
  let codeExamplesSection = "";
  if (facts.architecture.codeExamples && facts.architecture.codeExamples.length > 0) {
    const examples = facts.architecture.codeExamples
      .map((ex) => {
        // Detect language from file extension
        const ext = ex.file.split('.').pop() || '';
        const langMap: Record<string, string> = {
          ts: "typescript",
          tsx: "typescript",
          js: "javascript",
          jsx: "javascript",
          py: "python",
          go: "go",
          rs: "rust",
          java: "java",
          rb: "ruby",
          php: "php",
          cs: "csharp",
          cpp: "cpp",
          c: "c",
        };
        const lang = langMap[ext] || ext;
        
        return `### ${ex.title}

**File:** \`${ex.file}\`

\`\`\`${lang}
${ex.code}
\`\`\`

${ex.explanation}`;
      })
      .join("\n\n");
    
    codeExamplesSection = `## Code Examples

${examples}

`;
  }

  // Generate Mermaid diagram
  const mermaidDiagram = generateMermaidDiagram(facts);

  return `# Architecture: ${facts.repoName}

## Overview

${facts.architecture.overview}
${sourcesSection(facts.architecture.sources)}

## System Diagram

\`\`\`mermaid
${mermaidDiagram}
\`\`\`

## Components

${components}

${codeExamplesSection}## Data Flow

${facts.architecture.dataFlow || "_Data flow not documented_"}

## Key Abstractions

${abstractions}

## Entrypoints

| Path | Type | Description |
|------|------|-------------|
${facts.structure.entrypoints.length > 0
  ? facts.structure.entrypoints.map((e) => `| \`${e.path}\` | ${e.type} | ${e.description || "-"} |`).join("\n")
  : "| _None detected_ | - | - |"}

## Where to Change What

| Task | Location |
|------|----------|
| Add a new feature | \`${facts.structure.keyDirs.find((d) => d.purpose.toLowerCase().includes("source") || d.purpose.toLowerCase().includes("main"))?.path || "src/"}\` |
| Add tests | \`${facts.structure.testDirs[0] || "tests/"}\` |
| Modify build | \`${facts.stack.buildSystem === "npm" ? "package.json" : "build config"}\` |
| Update CI | \`${facts.ci.workflows[0]?.file || ".github/workflows/"}\` |

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
}

/**
 * Generate a Mermaid diagram from repo facts
 */
function generateMermaidDiagram(facts: RepoFacts): string {
  const components = facts.architecture.components;

  if (components.length === 0) {
    return `graph LR
    A[Entry] --> B[Core]
    B --> C[Output]`;
  }

  const nodes = components.map((c, i) => `    ${String.fromCharCode(65 + i)}["${c.name}"]`);
  const links: string[] = [];

  // Create simple linear flow if no dataFlow specified
  for (let i = 0; i < components.length - 1; i++) {
    links.push(`    ${String.fromCharCode(65 + i)} --> ${String.fromCharCode(66 + i)}`);
  }

  return `graph LR
${nodes.join("\n")}
${links.join("\n")}`;
}

/**
 * Generate CODEMAP.md
 */
export function generateCodemap(facts: RepoFacts): string {
  const dirs = facts.structure.keyDirs
    .map((d) => {
      const files = d.keyFiles?.map((f) => `  - \`${f}\``).join("\n") || "";
      return `### \`${d.path}\`

${d.purpose}

${files ? `Key files:\n${files}` : ""}`;
    })
    .join("\n\n");

  const entrypoints = facts.structure.entrypoints
    .map((e) => `- [\`${e.path}\`](./${e.path}) - ${e.description || e.type}`)
    .join("\n");

  return `# Code Map: ${facts.repoName}

A guided tour of the codebase for new contributors.

## Start Here

${entrypoints}

These are the main entry points to understand how the code flows.

## Directory Guide

${dirs}

## Test Structure

| Directory | Purpose |
|-----------|---------|
${facts.structure.testDirs.length > 0 
  ? facts.structure.testDirs.map((d) => `| \`${d}\` | Test files |`).join("\n")
  : "| _None detected_ | - |"}

## CI/CD

| Workflow | Triggers |
|----------|----------|
${facts.ci.workflows.length > 0
  ? facts.ci.workflows.map((w) => `| \`${w.file}\` | ${w.triggers.join(", ") || "-"} |`).join("\n")
  : "| _None detected_ | - |"}

## Reading Order for New Contributors

1. Start with the README
2. Look at the main entry point: \`${facts.structure.entrypoints[0]?.path || "src/index.ts"}\`
3. Trace through one user flow
4. Read the tests to understand expected behavior
5. Check CI to understand quality gates

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
}

/**
 * Generate FIRST_TASKS.md
 */
export function generateFirstTasks(facts: RepoFacts): string {
  const tasksByCategory = {
    beginner: facts.firstTasks.filter((t) => t.difficulty === "beginner"),
    intermediate: facts.firstTasks.filter((t) => t.difficulty === "intermediate"),
    advanced: facts.firstTasks.filter((t) => t.difficulty === "advanced"),
  };

  const formatTask = (t: (typeof facts.firstTasks)[0]) => `### ${t.title}

**Difficulty:** ${t.difficulty} | **Category:** ${t.category}

${t.description}

**Why this matters:** ${t.why}

**Files to look at:**
${t.files.map((f) => `- \`${f}\``).join("\n")}
`;

  return `# First Tasks: ${facts.repoName}

Suggested starter tasks for new contributors, organized by difficulty.

## Beginner Tasks (Safe Small Wins)

${tasksByCategory.beginner.map(formatTask).join("\n") || "_No beginner tasks suggested_"}

## Intermediate Tasks

${tasksByCategory.intermediate.map(formatTask).join("\n") || "_No intermediate tasks suggested_"}

## Advanced Tasks

${tasksByCategory.advanced.map(formatTask).join("\n") || "_No advanced tasks suggested_"}

## How to Pick a Task

1. **New to the codebase?** Start with a beginner task
2. **Want to learn the architecture?** Pick an intermediate refactor
3. **Ready for a challenge?** Try an advanced feature task

## Before You Start

1. Read [ARCHITECTURE.md](./ARCHITECTURE.md) to understand the system
2. Check if there's an existing issue for the task
3. Create a feature branch
4. Write tests for your changes
5. Submit a PR referencing this task

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
}

/**
 * Generate RUNBOOK.md
 */
export function generateRunbook(facts: RepoFacts): string {
  // Check if runbook is applicable
  const notApplicable = facts.runbook?.applicable === false || 
    (!facts.runbook?.deploySteps?.length && 
     !facts.runbook?.observability?.length &&
     !facts.runbook?.incidents?.length);

  if (notApplicable) {
    return `# Runbook: ${facts.repoName}

> This repository is a library/tool and does not require operational runbook documentation.

For usage instructions, see [ONBOARDING.md](./ONBOARDING.md).

## Build & Release

${facts.quickstart.commands.find(c => c.name === "build")?.command 
  ? `\`\`\`bash\n${facts.quickstart.commands.find(c => c.name === "build")?.command}\n\`\`\`` 
  : "_No build command detected_"}

## Publishing (if applicable)

- Ensure all tests pass
- Update version in ${facts.stack.buildSystem === "npm" ? "package.json" : "config file"}
- Create a git tag
- Push to trigger CI/CD

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
  }

  const runbook = facts.runbook!;
  const deploySteps = runbook.deploySteps?.map((s, i) => `${i + 1}. ${s}`).join("\n") || "_Not documented_";
  const observability = runbook.observability?.map((o) => `- ${o}`).join("\n") || "_Not documented_";
  const incidents =
    runbook.incidents?.map((i) => `### ${i.name}\n\n**Check:** ${i.check}`).join("\n\n") || "_No incidents documented_";

  return `# Runbook: ${facts.repoName}

Operational guide for deploying and maintaining this service.
${sourcesSection(runbook.sources)}

## Deployment

${deploySteps}

## Observability

${observability}

## Incident Response

${incidents}

## Health Checks

- Check CI status on GitHub
- Verify deployment succeeded
- Monitor error rates post-deploy

---
*Generated by [Repo Bootcamp](https://github.com/repo-bootcamp)*
`;
}

/**
 * Generate Mermaid diagrams file
 */
export function generateDiagrams(facts: RepoFacts): string {
  const componentDiagram = generateMermaidDiagram(facts);

  return `# Diagrams: ${facts.repoName}

## Component Architecture

\`\`\`mermaid
${componentDiagram}
\`\`\`

## Directory Structure

\`\`\`mermaid
graph TD
${facts.structure.keyDirs.map((d, i) => `    D${i}["${d.path}"]`).join("\n")}
\`\`\`

## CI/CD Pipeline

\`\`\`mermaid
graph LR
    A[Push] --> B[CI]
    B --> C{Tests Pass?}
    C -->|Yes| D[Build]
    C -->|No| E[Fix]
    D --> F[Deploy]
\`\`\`
`;
}
