/**
 * Auto-Issue Creator Module
 * Creates GitHub issues from FIRST_TASKS using the gh CLI
 */

import { execFile } from "child_process";
import { promisify } from "util";
import chalk from "chalk";
import type { FirstTask, RepoInfo } from "./types.js";
import { buildBlobUrl } from "./source-links.js";
import { parseGitHubUrl } from "./ingest.js";

const execFileAsync = promisify(execFile);

/** Validate the analyzed repository before invoking any GitHub CLI command. */
function githubIssueTarget(repoInfo: RepoInfo): string {
  try {
    const parsed = parseGitHubUrl(repoInfo.url);
    if (
      parsed.provider !== "github" ||
      (repoInfo.provider !== undefined && repoInfo.provider !== "github") ||
      (repoInfo.host !== undefined && repoInfo.host.toLowerCase() !== "github.com") ||
      parsed.owner.toLowerCase() !== repoInfo.owner.toLowerCase() ||
      parsed.repo.toLowerCase() !== repoInfo.repo.toLowerCase() ||
      parsed.fullName.toLowerCase() !== repoInfo.fullName.toLowerCase()
    ) {
      throw new Error("Repository metadata does not identify the same GitHub repository");
    }
    // Explicitly qualify the host so GH_HOST cannot redirect these operations.
    return `github.com/${parsed.fullName}`;
  } catch {
    throw new Error(
      "Automatic issue creation requires matching GitHub repository metadata. Use --create-issues --dry-run to export tasks for manual issue creation."
    );
  }
}

function supportsAutomaticIssues(repoInfo: RepoInfo): boolean {
  try {
    githubIssueTarget(repoInfo);
    return true;
  } catch {
    return false;
  }
}

/** Render a file path as a clickable remote link when possible, else bare code. */
function fileLink(filePath: string, repoInfo: RepoInfo): string {
  const url = buildBlobUrl(repoInfo, filePath);
  return url ? `[\`${filePath}\`](${url})` : `\`${filePath}\``;
}

/**
 * Issue to be created
 */
export interface IssuePayload {
  title: string;
  body: string;
  labels: string[];
}

/**
 * Result of issue creation
 */
export interface IssueResult {
  success: boolean;
  url?: string;
  error?: string;
  /** True when an issue with the same title already exists, including one
   *  successfully created earlier in this batch. */
  skipped?: boolean;
  payload: IssuePayload;
}

/**
 * Check if gh CLI is available and authenticated
 */
export async function checkGhAuth(): Promise<{
  available: boolean;
  authenticated: boolean;
  error?: string;
}> {
  try {
    await execFileAsync("which", ["gh"]);
  } catch {
    return { available: false, authenticated: false, error: "gh CLI not installed" };
  }

  try {
    await execFileAsync("gh", ["auth", "status"]);
    return { available: true, authenticated: true };
  } catch {
    return {
      available: true,
      authenticated: false,
      error: "gh CLI not authenticated. Run 'gh auth login' first.",
    };
  }
}

/**
 * Map difficulty to label
 */
function difficultyToLabel(difficulty: FirstTask["difficulty"]): string {
  switch (difficulty) {
    case "beginner":
      return "good first issue";
    case "intermediate":
      return "help wanted";
    case "advanced":
      return "enhancement";
  }
}

/**
 * Map category to label
 */
function categoryToLabel(category: FirstTask["category"]): string {
  switch (category) {
    case "bug-fix":
      return "bug";
    case "test":
      return "testing";
    case "docs":
      return "documentation";
    case "refactor":
      return "refactor";
    case "feature":
      return "enhancement";
  }
}

/**
 * Convert a FirstTask to an issue payload
 */
export function taskToIssuePayload(task: FirstTask, repoInfo: RepoInfo): IssuePayload {
  const body = `## Description

${task.description}

## Why This Task?

${task.why}

## Difficulty

**${task.difficulty.charAt(0).toUpperCase() + task.difficulty.slice(1)}** - ${
    task.difficulty === "beginner"
      ? "Great for newcomers!"
      : task.difficulty === "intermediate"
        ? "Some familiarity with the codebase helpful."
        : "Requires deep understanding of the codebase."
  }

## Files to Look At

${task.files.map((f) => `- ${fileLink(f, repoInfo)}`).join("\n")}

---

*This issue was auto-generated by [Repo Bootcamp](https://github.com/Arthur742Ramos/repo-bootcamp).*
`;

  return {
    title: task.title,
    body,
    labels: [difficultyToLabel(task.difficulty), categoryToLabel(task.category)],
  };
}

/**
 * Create a single GitHub issue
 */
async function createIssue(payload: IssuePayload, repoTarget: string): Promise<IssueResult> {
  try {
    // Build arguments array (safe from shell injection)
    const args = [
      "issue",
      "create",
      "--repo",
      repoTarget,
      "--title",
      payload.title,
      "--body",
      payload.body,
    ];

    // Add labels
    for (const label of payload.labels) {
      args.push("--label", label);
    }

    const { stdout } = await execFileAsync("gh", args, { timeout: 30000 });
    const url = stdout.trim();

    return {
      success: true,
      url,
      payload,
    };
  } catch (error: unknown) {
    return {
      success: false,
      error: (error as Error).message,
      payload,
    };
  }
}

/**
 * Fetch the titles of existing issues (any state) so re-runs can skip
 * duplicates instead of flooding the tracker. Best-effort: if `gh issue list`
 * fails (network, permissions, or a repo with issues disabled) we return an
 * empty set and fall back to creating everything rather than aborting.
 */
async function fetchExistingIssueTitles(repoFullName: string): Promise<Set<string>> {
  try {
    const { stdout } = await execFileAsync(
      "gh",
      [
        "issue",
        "list",
        "--repo",
        repoFullName,
        "--state",
        "all",
        "--limit",
        "200",
        "--json",
        "title",
      ],
      { timeout: 30000 }
    );
    const parsed = JSON.parse(stdout) as unknown;
    if (!Array.isArray(parsed)) return new Set();
    return new Set(
      parsed
        .map((item) =>
          item && typeof (item as { title?: unknown }).title === "string"
            ? (item as { title: string }).title
            : null
        )
        .filter((title): title is string => title !== null)
    );
  } catch (error: unknown) {
    console.log(
      chalk.yellow(
        `  Warning: could not list existing issues (${(error as Error).message}); skipping duplicate check.`
      )
    );
    return new Set();
  }
}

/**
 * Create issues for all first tasks
 */
export async function createIssuesFromTasks(
  tasks: FirstTask[],
  repoInfo: RepoInfo,
  options: { dryRun?: boolean; verbose?: boolean } = {}
): Promise<IssueResult[]> {
  const results: IssueResult[] = [];
  const repoTarget = options.dryRun ? "" : githubIssueTarget(repoInfo);

  // Check gh CLI availability
  if (!options.dryRun) {
    const auth = await checkGhAuth();
    if (!auth.available) {
      console.error(
        chalk.red("Error: gh CLI not found. Please install it from https://cli.github.com")
      );
      throw new Error("gh CLI not available");
    }
    if (!auth.authenticated) {
      console.error(chalk.red("Error: gh CLI not authenticated. Run 'gh auth login' first."));
      throw new Error("gh CLI not authenticated");
    }
  }

  // Fetch existing titles once so a second `--create-issues` run (or a
  // scheduled refresh) does not re-create the same tasks. Dry runs don't hit
  // the network — they just preview every task.
  const existingTitles = options.dryRun
    ? new Set<string>()
    : await fetchExistingIssueTitles(repoTarget);

  console.log(
    chalk.cyan(`\n${options.dryRun ? "[DRY RUN] " : ""}Creating ${tasks.length} issues...\n`)
  );

  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    const payload = taskToIssuePayload(task, repoInfo);

    console.log(chalk.white(`[${i + 1}/${tasks.length}] ${payload.title}`));
    console.log(chalk.gray(`  Labels: ${payload.labels.join(", ")}`));

    if (existingTitles.has(payload.title)) {
      results.push({ success: true, skipped: true, payload });
      console.log(chalk.gray("  Skipped: an issue with this title already exists"));
      continue;
    }

    if (options.dryRun) {
      // Just show preview
      if (options.verbose) {
        console.log(chalk.gray(`  Body preview: ${payload.body.substring(0, 100)}...`));
      }
      results.push({
        success: true,
        payload,
      });
      console.log(chalk.yellow("  [DRY RUN] Would create issue"));
    } else {
      const result = await createIssue(payload, repoTarget);
      results.push(result);

      if (result.success) {
        existingTitles.add(payload.title);
        console.log(chalk.green(`  Created: ${result.url}`));
      } else {
        console.log(chalk.red(`  Failed: ${result.error}`));
      }

      // Small delay to avoid rate limiting
      await new Promise((r) => setTimeout(r, 500));
    }
  }

  // Summary
  const skipped = results.filter((r) => r.skipped).length;
  const successful = results.filter((r) => r.success && !r.skipped).length;
  const failed = results.filter((r) => !r.success).length;

  console.log();
  if (options.dryRun) {
    console.log(chalk.yellow(`[DRY RUN] Would create ${successful} issues`));
    console.log(
      chalk.gray(
        supportsAutomaticIssues(repoInfo)
          ? "Run without --dry-run to actually create issues."
          : "Use the exported preview to create issues manually in your repository's tracker."
      )
    );
  } else {
    console.log(chalk.green(`Created: ${successful} issues`));
    if (skipped > 0) {
      console.log(chalk.gray(`Skipped: ${skipped} existing issues`));
    }
    if (failed > 0) {
      console.log(chalk.red(`Failed: ${failed} issues`));
    }
  }

  return results;
}

/**
 * Generate preview markdown for issues
 */
export function generateIssuePreview(tasks: FirstTask[], repoInfo: RepoInfo): string {
  const lines: string[] = [];
  const automatic = supportsAutomaticIssues(repoInfo);

  lines.push("# Issue Preview");
  lines.push("");
  lines.push(
    automatic
      ? `The following ${tasks.length} issues would be created in **${repoInfo.fullName}**:`
      : `The following ${tasks.length} tasks are ready for manual issue creation in **${repoInfo.fullName}**:`
  );
  lines.push("");

  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    const payload = taskToIssuePayload(task, repoInfo);

    lines.push(`## ${i + 1}. ${payload.title}`);
    lines.push("");
    lines.push(`**Labels:** ${payload.labels.join(", ")}`);
    lines.push("");
    lines.push("<details>");
    lines.push("<summary>Issue Body</summary>");
    lines.push("");
    lines.push(payload.body);
    lines.push("");
    lines.push("</details>");
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("## Commands");
  lines.push("");
  if (automatic) {
    lines.push("To create these issues, run:");
    lines.push("```bash");
    lines.push("bootcamp <repo-url> --create-issues");
    lines.push("```");
    lines.push("");
  } else {
    lines.push(
      "Copy the titles and bodies above into your repository's issue tracker. Automatic issue creation supports GitHub repositories only."
    );
    lines.push("");
  }
  lines.push("To preview without creating:");
  lines.push("```bash");
  lines.push("bootcamp <repo-url> --create-issues --dry-run");
  lines.push("```");

  return lines.join("\n");
}
