/**
 * Types for Repo Bootcamp Generator
 */

import type { OutputFormat } from "./formatter.js";

// CLI Options
export interface BootcampOptions {
  branch: string;
  focus: "onboarding" | "architecture" | "contributing" | "all";
  audience: "new-hire" | "oss-contributor" | "internal-dev";
  output: string;
  maxFiles: number;
  noClone: boolean;
  verbose: boolean;
  model?: string;
  keepTemp?: boolean;
  jsonOnly?: boolean;
  stats?: boolean;
  fast?: boolean;
  // New features
  interactive?: boolean;
  transcript?: boolean;
  compare?: string;
  createIssues?: boolean;
  dryRun?: boolean;
  format?: OutputFormat;
  renderDiagrams?: boolean;
  diagramFormat?: "svg" | "png" | "pdf";
  style?: "startup" | "enterprise" | "oss" | "devops";
  web?: boolean;
  fullClone?: boolean;
  watch?: boolean;
  watchInterval?: number;
  noCache?: boolean;
  repoPrompts?: string;
}

// Template style pack
export type StylePack = "startup" | "enterprise" | "oss" | "devops";

// Tech Radar signal
export interface RadarSignal {
  name: string;
  category: "modern" | "stable" | "legacy" | "risky";
  reason: string;
}

// Tech Radar result
export interface TechRadar {
  modern: RadarSignal[];
  stable: RadarSignal[];
  legacy: RadarSignal[];
  risky: RadarSignal[];
  onboardingRisk: {
    score: number; // 0-100, lower is better (less risky)
    grade: string; // A-F
    factors: string[];
  };
}

// Change impact result
export interface ChangeImpact {
  file: string;
  affectedFiles: string[];
  affectedTests: string[];
  affectedDocs: string[];
  importedBy: string[];
  imports: string[];
}

// Diff summary
export interface DiffSummary {
  baseRef: string;
  headRef: string;
  filesChanged: number;
  filesAdded: string[];
  filesRemoved: string[];
  filesModified: string[];
  onboardingDeltas: {
    newDependencies: string[];
    removedDependencies: string[];
    newEnvVars: string[];
    newCommands: string[];
    breakingChanges: string[];
  };
}

// Interactive session message
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  citations?: string[];
  timestamp: Date;
}

// Interactive session transcript
export interface Transcript {
  repoName: string;
  startedAt: Date;
  messages: ChatMessage[];
}

// Parsed repo URL
export interface RepoInfo {
  owner: string;
  repo: string;
  url: string;
  branch: string;
  fullName: string;
  commitSha?: string;
}

// Stack detection results
export interface StackInfo {
  languages: string[];
  frameworks: string[];
  buildSystem: string;
  packageManager: string | null;
  hasDocker: boolean;
  hasCi: boolean;
}

// Entrypoint detection
export interface Entrypoint {
  path: string;
  type: "main" | "binary" | "server" | "cli" | "web" | "library";
  description?: string;
}

// Command discovery
export interface Command {
  name: string;
  command: string;
  source: string; // e.g., "package.json", "Makefile"
  description?: string;
}

// CI workflow info
export interface CIWorkflow {
  name: string;
  file: string;
  triggers: string[];
  mainSteps: string[];
}

// Directory info
export interface DirectoryInfo {
  path: string;
  purpose: string;
  keyFiles?: string[];
}

// First task suggestion
export interface FirstTask {
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  category: "bug-fix" | "test" | "docs" | "refactor" | "feature";
  files: string[];
  why: string;
}

// The main repo facts structure (generated by LLM)
export interface RepoFacts {
  repoName: string;
  purpose: string;
  description: string;
  confidence?: "high" | "medium" | "low";
  sources?: string[];
  stack: StackInfo;
  quickstart: {
    prerequisites: string[];
    steps: string[];
    commands: Command[];
    commonErrors?: { error: string; fix: string }[];
    sources?: string[];
  };
  structure: {
    keyDirs: DirectoryInfo[];
    entrypoints: Entrypoint[];
    testDirs: string[];
    docsDirs: string[];
    sources?: string[];
  };
  ci: {
    workflows: CIWorkflow[];
    mainChecks: string[];
    sources?: string[];
  };
  contrib: {
    howToAddFeature: string[];
    howToAddTest: string[];
    codeStyle?: string;
    sources?: string[];
  };
  architecture: {
    overview: string;
    components: { name: string; description: string; directory: string }[];
    dataFlow?: string;
    keyAbstractions?: { name: string; description: string }[];
    codeExamples?: { title: string; file: string; code: string; explanation: string }[];
    sources?: string[];
  };
  firstTasks: FirstTask[];
  runbook?: {
    applicable?: boolean;
    deploySteps?: string[];
    observability?: string[];
    incidents?: { name: string; check: string }[];
    sources?: string[];
  };
}

// File info collected during scanning
export interface FileInfo {
  path: string;
  size: number;
  isDirectory: boolean;
}

// Scan results
export interface ScanResult {
  files: FileInfo[];
  stack: StackInfo;
  commands: Command[];
  ciWorkflows: CIWorkflow[];
  readme: string | null;
  contributing: string | null;
  keySourceFiles: Map<string, string>;
}
